# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Jordan Poles
tagline:          'Exploring Life Through Code'
description:      "I'm a student at Rice University studying Biosciences, Statistics, and PJHC. I love to code, and tinker! Join me as I explore my world."
url:              http://jpoles1.github.io/blog/
baseurl:          /blog/

author:
  name:           'Jordan Poles'
  url:            http://jpoles1.github.io

#Pagination
gems :
  - jekyll-paginate
  - jekyll-gist
paginate: 5
paginate_path: "page:num"

github:
  repo:           https://github.com/jpoles1/blog
